### ISSUE TITLE
Could not acquire or refresh tokens [http 400]

### ISSUE THREAD

**Issue by TutanRamon** [websmurf/laravel-exact-online#10]
Hi there,

Yesterday I succesfully deployed your Laravel wrapper to my Laravel-app (localhost). I was able to make queries to the Exact api. Today, I wanted to connect to the API again, but got the error "Could not acquire or refresh tokens [http 400]" after pressing the button "connect to Exact".

I am basically familair with the OAuth of Exact. Is there anything I can do manually to reconnect? I installed the package yesterday, so I believe i am running the latest version. Thanks in advance.

**Comment by websmurf** [comment]
Sounds a lot like https://github.com/picqer/exact-php-client/issues/359 or https://github.com/picqer/exact-php-client/issues/385, but never heard or had it in the authorization process before.

Normally, a JSON file should be stored on your system with the authentication tokens after the first authentication attempt. Once the token expires a new valid token will be fetched automatically. You shouldn't have to press the connect button again until the token really expires and re-fetching fails a well.

**Comment by TutanRamon** [comment]
OK, I checked the json file and noticed that the timestamp was already expired. I cleared the file and pressed the "Connect to Exact" button again. Now, I didn't needed to enter my credentials and was redirected to "Your app is now connected" page. 

However, when checking the json file again, i notice the exact_tokenExpires is set to 1637838773 (which is 10 minutes after it was released).

**Comment by websmurf** [comment]
That's intended behaviour. The token Exact issues is valid for 10 minutes, after which the refresh token (that's also in the JSON file) can be used to fetch a new access token (which then can be used for 10 minutes again)

**Comment by websmurf** [comment]
This is described here: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-devstep3 and here: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-devstep4

**Comment by TutanRamon** [comment]
Thanks, I see. And thanks for creating this Laravel Wrapper!

**Comment by websmurf** [comment]
You're welcome :-)
