### ISSUE TITLE
setDivision()

### ISSUE THREAD

**Issue by TutanRamon** [websmurf/laravel-exact-online#11]
Hi there,

How can I utilize the $connection->setDivision($x) method from Picqer?

For the purpose of learning and understanding, I added this method to the LaravelExactOnline class, but it doesn't work:

    public static function setDivision(Connection $connection, $division): void
    {
        $connection->setDivision($division);
    }

**Comment by TutanRamon** [comment]
Sorry, I missed something in the readme. 

I can just use ExactOnline::connectionSetDivision. :-) Nice!

**Comment by websmurf** [comment]
Is there anything else you needed to know?

**Comment by TutanRamon** [comment]
No, that's all.

**Comment by taransaini100** [comment]
ExactOnline::connectionSetDivision how can we use that? 

Whenever i am doing so getting error that ExactOnline Class not exist.
Even when using that class inside LaravelExactOnline class. 
Error:
Class 'Websmurf\LaravelExactOnline\ExactOnline' not found

Can someone help me with this please?

**Comment by TutanRamon** [comment]
> ExactOnline::connectionSetDivision how can we use that?
> 
> Whenever i am doing so getting error that ExactOnline Class not exist. Even when using that class inside LaravelExactOnline class. Error: Class 'Websmurf\LaravelExactOnline\ExactOnline' not found
> 
> Can someone help me with this please?

Can you post the file which is giving this error?

**Comment by taransaini100** [comment]
> Can you post the file which is giving this error?

Actually, I am using this class in a laravel controller
use Websmurf\LaravelExactOnline\LaravelExactOnline;

And this is the function which giving error:

public function updateExactDomain(Request $request){	
	    if(Auth::user()){
		    $user = Auth::user();
		    $userResponse = $user->getAttributes();
		    $userid = $userResponse['ID'];
		    $_POST = $request->all();
		    if(isset($_POST['exact_domain']) && !empty($_POST['exact_domain'])){
			    //$select = 'https://start.exactonline.'. $_POST['exact_domain'];
			    ExactOnline::connectionSetBaseUrl('http://start.exactonline.de')
		    }
	    }
	    return redirect('/app/connections');	
}
	
And even i tried make function inside the LaravelExactOnline class in which doing same call for update base url but same error that ExactOnline class not exist.

Can you please share me the location of ExactOnline class in sdk?

**Comment by TutanRamon** [comment]
You are referencing the wrong class. Where do you define "ExactOnline" .... ?

You should use this instead:

    use Websmurf\LaravelExactOnline\LaravelExactOnlineFacade as ExactOnline;
