### ISSUE TITLE
Use with cron / task

### ISSUE THREAD

**Issue by TutanRamon** [websmurf/laravel-exact-online#13]
I have a question regarding the use of task schedules in Laravel. 

I created a job that uses your library to connect to Exact, with multi_user enabled. When I am logged in to my app I can start the job manually which fetches the latest data from Exact. That's working. Now, I want to schedule a task which executes the job every night. But I am strugling a bit. Somehow, I need to use an "User" in the sync job (to update the refresh tokens etc.).

What's the best approach for this?

Update:
For the sake of trial and error: I changed https://github.com/websmurf/laravel-exact-online/blob/56639c3c912d579726070496415df46a4d68a41d/src/LaravelExactOnline.php#L450 to 
**return \App\Models\User::find(1)**  but that's not working. (I was planning to override this method, so I thought this was worth trying before creating the override class.)

**Comment by websmurf** [comment]
Perhaps you can try to use the actingAs helper? 

https://laravel.com/docs/8.x/http-tests#session-and-authentication

Normally it's used in tests; but I think it's not limited to that.

**Comment by websmurf** [comment]
Closed due to lack of response
