### ISSUE TITLE
Only instantiate ExactOnline if it's required, not always

### ISSUE THREAD

**Issue by websmurf** [websmurf/laravel-exact-online#2]
At this point if a connection error occurs (resulting in the infamous 401 Could not acquire or refresh tokens error) all other code will fail to execute as well (since it just stops at this). 

Since we only need to check the connection if we actually use the ExactOnline object, we only need to instantiate the class at that point as well.

**Comment by wouterdoublebyte** [comment]
Any updates on this?

**Comment by websmurf** [comment]
Implemented by #9
