### ISSUE TITLE
How do you log & access the response object? E.g: need to create a user and then access the user's guid from response and save it locally

### ISSUE THREAD

**Issue by RenoSimonsWebit** [websmurf/laravel-exact-online#20]

**Comment by websmurf** [comment]
Hi Reno,

If you use the regular save action, it will hydrate the current object with the updated details: https://github.com/picqer/exact-php-client/blob/main/src/Picqer/Financials/Exact/Persistance/Storable.php#L48

That will mean you can do something like this:
```php
$user = new User($connection);
$user->Email = 'test@test.nl';
...
..
$user->save();

var_dump($user->UserID); // should have the id
```

**Comment by RenoSimonsWebit** [comment]
Thanks Websmurf! Issue resolved, thanks for the fast response, have a nice day!
