### ISSUE TITLE
Callback URI is not valid

### ISSUE THREAD

**Issue by y-dewert** [websmurf/laravel-exact-online#8]
Since the update of the Exact Online API that I need an HTTPS callback URI, the package no longer works.

I have installed an SSL certificate on my development environment and it still doesn't work. I keep getting the error "Callback URI 'https://mycompany.test/exact/oauth' is not valid", but in the App Center I entered "https://mycompany.test" as my callback URI.

**Comment by websmurf** [comment]
You need to use the exact callback url, so in the Exact Online app centre, you'll need to enter `https://mycompany.test/exact/oauth` as your redirect URI

**Comment by websmurf** [comment]
In lack of any further response; I'm closing this issue. 
Please reopen if needed.
